--- #YAML:1.0
name:                Finance-Bank-NetBranch
version:             0.07
abstract:            Manage your NetBranch accounts with Perl
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Alias:                         0
    Carp:                          0
    Date::Parse:                   0
    DateTime:                      0
    HTML::Entities:                0
    HTML::TreeBuilder:             0
    Test::More:                    0
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Darren Kulp <darren@kulp.ch>
